Docs update 3
react-page/react-page pull request #955
Opened 2021-04-13 10:59 UTC by zehawki

The Inbuilt Plugins section of the docs is also updated.

2021-04-13 11:08 UTC, zehawki commented
@macrozone I see that the diff for sidebar.md (https://github.com/react-page/react-page/pull/955/files#diff-2a55b1a76ffb4ba683697763144889d5759e3f6204a8b54e94d41435523c6f97) shows a `[Recipes & Tips](/recipes.md)` link, but I've never seen that in the docs...

2021-04-20 12:40 UTC, zehawki commented
@macrozone this is still pending, BTW

2021-04-20 12:44 UTC, macrozone commented
there are unanswered questions

2021-04-20 12:45 UTC, zehawki commented
>there are unanswered questions

Sorry, didnt get. Where do I see these?

2021-04-20 12:46 UTC, macrozone requested changes

2021-04-20 12:49 UTC, macrozone commented
ah sorry, forgot to click

2021-04-22 18:32 UTC, zehawki commented on docs/quick-start.md
> -(see demo here)](//demo/examples/readonly)
1. This section is "getting started" - it does not need to provide every bit of info
2. It does not make sense to have the same piece of code repeated in multiple places - over time, with different collaborators etc, these diverge and cause confusion in new users mind. This was the same problem I faced when I first started - the two pieces of code showed different things
3. A full, relevant example is just below, in the next section: Editor component

2021-05-05 19:43 UTC, zehawki commented
@macrozone did you get a chance to see my replies? I'm afraid the longer the changes are not merged, the more they may conflict later.

2021-06-01 11:30 UTC, macrozone requested changes

2021-06-01 11:31 UTC, macrozone commented
sorry i forgot to submit the review

2021-06-18 12:31 UTC, merged

2021-06-18 12:42 UTC, macrozone commented
:tada: This PR is included in version 3.1.1 :tada:

The release is available on:
- `v3.1.1`
- [GitHub release](https://github.com/react-page/react-page/releases/tag/v3.1.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: